#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
NAME=linker
PROG=/usr/bin/linker/linker
WORKDIR=/usr/bin/linker

EXTRA_COMMANDS="status"
EXTRA_HELP="	status	Print service status"

start_service() {
	[ -x "$PROG" ] || {
		echo "$PROG is missing or not executable"
		return 1
	}

	procd_open_instance "$NAME"
	procd_set_param command "$PROG"
	procd_set_param cwd "$WORKDIR"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

restart() {
	stop
	start
}

status() {
	if pidof linker >/dev/null 2>&1; then
		echo "linker is running."
		return 0
	fi

	echo "linker is not running."
	return 1
}
