using System;
using System.Buffers.Binary;
using System.Diagnostics;

namespace linker.fec;

/// <summary>
/// Low-latency wrapper around <see cref="LinkerFecCodec"/>. Source frames are emitted immediately;
/// repair frames are generated by the inner encoder when a block is full, expired, forced, or final.
/// </summary>
public sealed class LinkerFecStreamingEncoder : IDisposable
{
    private readonly object _syncRoot = new();
    private readonly LinkerFecCodec _encoder;
    private readonly LinkerFecCodec _decoder;
    private readonly byte[] _recordBuffer;
    private readonly byte[] _codecBuffer;
    private readonly bool[] _sourceFrameWritten;
    private int _recordBytes;
    private int _sourceCount;
    private long _blockStartedTimestamp;
    private ulong _nextBlockId;
    private ulong _currentBlockId;
    private bool _hasCurrentBlock;
    private bool _completed;
    private bool _disposed;

    public LinkerFecStreamingEncoder(LinkerFecOptions? options = null, TimeSpan? repairTimeout = null)
    {
        Options = options ?? new LinkerFecOptions();
        Options.Validate();
        RepairTimeout = repairTimeout ?? TimeSpan.FromMilliseconds(8);
        if (RepairTimeout < TimeSpan.Zero)
        {
            throw new ArgumentOutOfRangeException(nameof(repairTimeout), repairTimeout, "Repair timeout cannot be negative.");
        }

        _encoder = new LinkerFecCodec(Options);
        _decoder = new LinkerFecCodec(Options);
        _recordBuffer = new byte[Options.MaxRecordListSize];
        _codecBuffer = new byte[Options.MaxEncodeBufferSize];
        _sourceFrameWritten = new bool[Options.SourceSymbolsPerBlock];
    }

    public LinkerFecOptions Options { get; }

    public TimeSpan RepairTimeout { get; }

    public int PendingSourceCount
    {
        get
        {
            lock (_syncRoot)
            {
                return _sourceCount;
            }
        }
    }

    public int MaxOutputBufferSize => checked(Options.MaxEncodeBufferSize + GetMaxRepairOutputSize());

    public int EncodePacket(
        ReadOnlySpan<byte> rawPacket,
        Span<byte> destination,
        out int packetCount,
        bool isFinalPacket = false)
    {
        if (!TryEncodePacket(rawPacket, destination, out var bytesWritten, out packetCount, isFinalPacket))
        {
            throw new ArgumentException("Destination buffer is too small for the encoded streaming packet.", nameof(destination));
        }

        return bytesWritten;
    }

    public bool TryEncodePacket(
        ReadOnlyMemory<byte> rawPacket,
        Memory<byte> destination,
        out int bytesWritten,
        out int packetCount,
        bool isFinalPacket = false)
    {
        return TryEncodePacket(rawPacket.Span, destination.Span, out bytesWritten, out packetCount, isFinalPacket);
    }

    public bool TryEncodePacket(
        ReadOnlySpan<byte> rawPacket,
        Span<byte> destination,
        out int bytesWritten,
        out int packetCount,
        bool isFinalPacket = false)
    {
        lock (_syncRoot)
        {
            ThrowIfDisposed();
            bytesWritten = 0;
            packetCount = 0;

            if (_completed)
            {
                throw new InvalidOperationException("Streaming packet input has already been completed.");
            }

            Span<int> sourceOffsets = stackalloc int[Options.SourceSymbolsPerBlock];
            Span<int> sourceLengths = stackalloc int[Options.SourceSymbolsPerBlock];
            var inputSourceCount = BuildSourceSegments(rawPacket, Options.SymbolSize, sourceOffsets, sourceLengths);

            var requiredSize = GetConservativeOutputSize(sourceLengths[..inputSourceCount], isFinalPacket);
            if (destination.Length < requiredSize)
            {
                return false;
            }

            for (var i = 0; i < inputSourceCount; i++)
            {
                var isLastInputSource = i == inputSourceCount - 1;
                var isFinalBlock = isFinalPacket && isLastInputSource;
                var sourceOffset = sourceOffsets[i];
                var sourceLength = sourceLengths[i];
                var payload = rawPacket.Slice(sourceOffset, sourceLength);

                if (!_hasCurrentBlock)
                {
                    StartBlock();
                }

                WriteStreamingSourceFrame(destination, ref bytesWritten, ref packetCount, _currentBlockId, _sourceCount, payload);
                _sourceFrameWritten[_sourceCount] = true;
                StoreRecord(rawPacket.Slice(sourceOffset - sizeof(int), sizeof(int) + sourceLength));

                if (_sourceCount == Options.SourceSymbolsPerBlock || isFinalBlock)
                {
                    if (!TryForceFlushRepairsCore(destination, ref bytesWritten, ref packetCount, isFinalBlock))
                    {
                        throw new InvalidOperationException("Streaming output size calculation is inconsistent.");
                    }
                }
            }

            if (isFinalPacket)
            {
                _completed = true;
            }

            return true;
        }
    }

    public int FlushRepairs(Span<byte> destination, out int packetCount, bool isFinalPacket = false)
    {
        if (!TryForceFlushRepairs(destination, out var bytesWritten, out packetCount, isFinalPacket))
        {
            throw new ArgumentException("Destination buffer is too small for the streaming repair frames.", nameof(destination));
        }

        return bytesWritten;
    }

    public bool TryFlushRepairs(
        Span<byte> destination,
        out int bytesWritten,
        out int packetCount,
        bool isFinalPacket = false)
    {
        lock (_syncRoot)
        {
            ThrowIfDisposed();
            bytesWritten = 0;
            packetCount = 0;

            if (_completed)
            {
                throw new InvalidOperationException("Streaming packet input has already been completed.");
            }

            if (_sourceCount == 0)
            {
                if (isFinalPacket)
                {
                    _completed = true;
                }

                return true;
            }

            if (Stopwatch.GetElapsedTime(_blockStartedTimestamp) < RepairTimeout)
            {
                return true;
            }

            return TryForceFlushRepairsCore(destination, ref bytesWritten, ref packetCount, isFinalPacket);
        }
    }

    public bool TryForceFlushRepairs(
        Span<byte> destination,
        out int bytesWritten,
        out int packetCount,
        bool isFinalPacket = false)
    {
        lock (_syncRoot)
        {
            ThrowIfDisposed();
            bytesWritten = 0;
            packetCount = 0;

            if (_completed)
            {
                throw new InvalidOperationException("Streaming packet input has already been completed.");
            }

            if (_sourceCount == 0)
            {
                if (isFinalPacket)
                {
                    _completed = true;
                }

                return true;
            }

            if (destination.Length < GetMaxRepairOutputSize())
            {
                return false;
            }

            return TryForceFlushRepairsCore(destination, ref bytesWritten, ref packetCount, isFinalPacket);
        }
    }

    public bool TryDecodeFrame(
        ReadOnlyMemory<byte> encodedFrame,
        Memory<byte> destination,
        out int bytesWritten)
    {
        return TryDecodeFrame(encodedFrame.Span, destination.Span, out bytesWritten, out _);
    }

    public bool TryDecodeFrame(
        ReadOnlyMemory<byte> encodedFrame,
        Memory<byte> destination,
        out int bytesWritten,
        out int packetCount)
    {
        return TryDecodeFrame(encodedFrame.Span, destination.Span, out bytesWritten, out packetCount);
    }

    public bool TryDecodeFrame(
        ReadOnlyMemory<byte> encodedFrame,
        Memory<byte> destination,
        Memory<LinkerFecDecodedPacketKind> packetKinds,
        out int bytesWritten,
        out int packetCount)
    {
        return TryDecodeFrame(encodedFrame.Span, destination.Span, packetKinds.Span, out bytesWritten, out packetCount);
    }

    public bool TryDecodeFrame(
        ReadOnlySpan<byte> encodedFrame,
        Span<byte> destination,
        out int bytesWritten)
    {
        return TryDecodeFrame(encodedFrame, destination, out bytesWritten, out _);
    }

    public bool TryDecodeFrame(
        ReadOnlySpan<byte> encodedFrame,
        Span<byte> destination,
        out int bytesWritten,
        out int packetCount)
    {
        lock (_syncRoot)
        {
            ThrowIfDisposed();
            return _decoder.TryDecodeFrame(encodedFrame, destination, out bytesWritten, out packetCount);
        }
    }

    public bool TryDecodeFrame(
        ReadOnlySpan<byte> encodedFrame,
        Span<byte> destination,
        Span<LinkerFecDecodedPacketKind> packetKinds,
        out int bytesWritten,
        out int packetCount)
    {
        lock (_syncRoot)
        {
            ThrowIfDisposed();
            return _decoder.TryDecodeFrame(encodedFrame, destination, packetKinds, out bytesWritten, out packetCount);
        }
    }

    public void Dispose()
    {
        lock (_syncRoot)
        {
            if (_disposed)
            {
                return;
            }

            _disposed = true;
            _encoder.Dispose();
            _decoder.Dispose();
        }
    }

    private void StartBlock()
    {
        _currentBlockId = _nextBlockId;
        _blockStartedTimestamp = Stopwatch.GetTimestamp();
        _hasCurrentBlock = true;
    }

    private void StoreRecord(ReadOnlySpan<byte> record)
    {
        if (record.Length > _recordBuffer.Length - _recordBytes)
        {
            throw new InvalidOperationException("Streaming record buffer is too small.");
        }

        record.CopyTo(_recordBuffer.AsSpan(_recordBytes));
        _recordBytes += record.Length;
        _sourceCount++;
    }

    private bool TryForceFlushRepairsCore(
        Span<byte> destination,
        ref int bytesWritten,
        ref int packetCount,
        bool isFinalPacket)
    {
        if (!_encoder.TryEncodePacket(
                _recordBuffer.AsSpan(0, _recordBytes),
                _codecBuffer.AsSpan(),
                out var codecBytesWritten,
                out _,
                isFinalPacket))
        {
            throw new InvalidOperationException("Inner FEC encoder did not fit in its maximum output buffer.");
        }

        var filteredSize = CountFilteredFrames(_codecBuffer.AsSpan(0, codecBytesWritten));
        if (filteredSize > destination.Length - bytesWritten)
        {
            throw new InvalidOperationException("Streaming repair frame output exceeded the precomputed size.");
        }

        CopyFilteredFrames(_codecBuffer.AsSpan(0, codecBytesWritten), destination, ref bytesWritten, ref packetCount);
        ClearCurrentBlock();
        _nextBlockId++;
        if (isFinalPacket)
        {
            _completed = true;
        }

        return true;
    }

    private int GetConservativeOutputSize(ReadOnlySpan<int> inputSourceLengths, bool isFinalPacket)
    {
        var sourceCount = _sourceCount;
        var size = 0;
        for (var i = 0; i < inputSourceLengths.Length; i++)
        {
            size = checked(size + sizeof(int) + LinkerFecEncodedSymbol.HeaderSize + inputSourceLengths[i]);
            sourceCount++;

            var shouldFlush = sourceCount == Options.SourceSymbolsPerBlock || (isFinalPacket && i == inputSourceLengths.Length - 1);
            if (shouldFlush)
            {
                size = checked(size + GetMaxRepairOutputSize());
                sourceCount = 0;
            }
        }

        return size;
    }

    private int GetMaxRepairOutputSize()
    {
        return checked(Options.MaxRepairSymbolsPerEncodedBlock *
            (sizeof(int) +
            LinkerFecEncodedSymbol.HeaderSize +
            LinkerFecEncodedSymbol.RepairLengthSymbolSize +
            Options.SymbolSize));
    }

    private int CountFilteredFrames(ReadOnlySpan<byte> encoded)
    {
        var offset = 0;
        var size = 0;
        while (offset < encoded.Length)
        {
            var frameLength = BinaryPrimitives.ReadInt32LittleEndian(encoded.Slice(offset, sizeof(int)));
            var frameOffset = offset + sizeof(int);
            var frame = encoded.Slice(frameOffset, frameLength);
            if (ShouldOutputFrame(frame))
            {
                size = checked(size + sizeof(int) + frameLength);
            }

            offset = frameOffset + frameLength;
        }

        return size;
    }

    private void CopyFilteredFrames(
        ReadOnlySpan<byte> encoded,
        Span<byte> destination,
        ref int bytesWritten,
        ref int packetCount)
    {
        var offset = 0;
        while (offset < encoded.Length)
        {
            var frameLength = BinaryPrimitives.ReadInt32LittleEndian(encoded.Slice(offset, sizeof(int)));
            var frameOffset = offset + sizeof(int);
            var frame = encoded.Slice(frameOffset, frameLength);
            if (ShouldOutputFrame(frame))
            {
                encoded.Slice(offset, sizeof(int) + frameLength).CopyTo(destination.Slice(bytesWritten));
                bytesWritten += sizeof(int) + frameLength;
                packetCount++;
            }

            offset = frameOffset + frameLength;
        }
    }

    private bool ShouldOutputFrame(ReadOnlySpan<byte> frame)
    {
        if (LinkerFecEncodedSymbol.IsRepairFrame(frame))
        {
            return true;
        }

        var symbolId = LinkerFecEncodedSymbol.ReadSymbolId(frame);
        return symbolId >= _sourceFrameWritten.Length || !_sourceFrameWritten[symbolId];
    }

    private void WriteStreamingSourceFrame(
        Span<byte> destination,
        ref int bytesWritten,
        ref int packetCount,
        ulong blockId,
        int symbolId,
        ReadOnlySpan<byte> packet)
    {
        var frameLength = LinkerFecEncodedSymbol.HeaderSize + packet.Length;
        BinaryPrimitives.WriteInt32LittleEndian(destination.Slice(bytesWritten, sizeof(int)), frameLength);
        bytesWritten += sizeof(int);
        LinkerFecEncodedSymbol.WriteStreamingSourceFrame(
            destination.Slice(bytesWritten, frameLength),
            blockId,
            symbolId,
            packet);
        bytesWritten += frameLength;
        packetCount++;
    }

    private static int BuildSourceSegments(
        ReadOnlySpan<byte> records,
        int symbolSize,
        Span<int> sourceOffsets,
        Span<int> sourceLengths)
    {
        if (records.Length < sizeof(int))
        {
            throw new ArgumentException("Expected at least one [4-byte length][payload] record.", nameof(records));
        }

        var offset = 0;
        var sourceCount = 0;
        while (offset < records.Length)
        {
            if (records.Length - offset < sizeof(int))
            {
                throw new ArgumentException("Record list ended inside a packet length prefix.", nameof(records));
            }

            var packetLength = BinaryPrimitives.ReadInt32LittleEndian(records.Slice(offset, sizeof(int)));
            if (packetLength < 0)
            {
                throw new ArgumentException("Packet length prefix cannot be negative.", nameof(records));
            }

            var recordLength = checked(sizeof(int) + packetLength);
            if (recordLength > records.Length - offset)
            {
                throw new ArgumentException("Packet length prefix exceeds the remaining payload bytes.", nameof(records));
            }

            if (packetLength > symbolSize)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(records),
                    packetLength,
                    "Each application payload must fit in one FEC source symbol.");
            }

            if (sourceCount == sourceOffsets.Length)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(records),
                    sourceCount + 1,
                    "Application record count exceeds the configured source symbol limit.");
            }

            sourceOffsets[sourceCount] = offset + sizeof(int);
            sourceLengths[sourceCount] = packetLength;
            sourceCount++;
            offset += recordLength;
        }

        return sourceCount;
    }

    private void ClearCurrentBlock()
    {
        Array.Clear(_sourceFrameWritten, 0, _sourceCount);
        _recordBytes = 0;
        _sourceCount = 0;
        _hasCurrentBlock = false;
    }

    private void ThrowIfDisposed()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
    }
}
