FROM alpine:latest

ENV TZ=Asia/Shanghai DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
RUN echo "https://mirrors.tuna.tsinghua.edu.cn/alpine/latest-stable/main/" > /etc/apk/repositories \
    && apk add --no-cache libstdc++ libintl tzdata zeromq bash \
    && ln -snf /usr/share/zoneinfo/$clTZ /etc/localtime \
    && echo $TZ > /etc/timezone

EXPOSE 1800/tcp
EXPOSE 1801/tcp
EXPOSE 1802/tcp
EXPOSE 1802/udp

WORKDIR /app
COPY . .



ENTRYPOINT ["./link.run"]