FROM alpine:latest

ENV TZ=Asia/Shanghai DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
RUN echo "https://mirrors.ustc.edu.cn/alpine/latest-stable/main/" > /etc/apk/repositories \
    && apk add --no-cache libstdc++ libintl tzdata zeromq bash \
    && ln -snf /usr/share/zoneinfo/$clTZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && apk add libmsquic


EXPOSE 1802/tcp
EXPOSE 1802/udp
EXPOSE 1803/tcp
EXPOSE 1803/udp
EXPOSE 1804/tcp
EXPOSE 1804/udp

WORKDIR /app
COPY . .

RUN chmod +x ./linker \
    && chmod +x ./plugins/tuntap/tun2socks


ENTRYPOINT ["./linker"]