FROM silentwind0/kvmd:latest

RUN ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo Asia/Shanghai > /etc/timezone
RUN apt update \
    && apt-get install -y --no-install-recommends iputils-ping \
    && apt-get install -y --no-install-recommends iproute2 \
    && apt-get install -y --no-install-recommends dmidecode \
    && apt-get install -y --no-install-recommends net-tools \
    && apt-get install -y --no-install-recommends curl \
    && apt-get install -y --no-install-recommends traceroute \
    && apt-get install -y --no-install-recommends iptables \
    && apt-get install -y --no-install-recommends ca-certificates \
    && curl -sSL -O https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y libmsquic \
    && apt-get purge -y --auto-remove wget && apt-get clean && rm -rf /var/lib/apt/lists/*


EXPOSE 1802/tcp
EXPOSE 1802/udp
EXPOSE 1803/tcp
EXPOSE 1803/udp
EXPOSE 1804/tcp
EXPOSE 1804/udp
EXPOSE 1806/tcp
EXPOSE 1806/udp
EXPOSE 1807/tcp
EXPOSE 1807/udp
EXPOSE 5900/tcp
EXPOSE 5900/udp
EXPOSE 623/tcp
EXPOSE 623/udp


COPY . /linker/
COPY kvm/__init__.py /kvmd/plugins/hid/ch9329/__init__.py

COPY kvm/index.html /usr/share/kvmd/web/linker/index.html
COPY kvm/logo-linker.png /usr/share/kvmd/web/share/svg/logo-linker.png
COPY kvm/logo.svg /usr/share/kvmd/web/share/svg/logo.svg
COPY kvm/favicon-16x16.png /usr/share/kvmd/web/share/favicon-16x16.png
COPY kvm/favicon-32x32.png /usr/share/kvmd/web/share/favicon-32x32.png
COPY kvm/apple-touch-icon.png /usr/share/kvmd/web/share/apple-touch-icon.png
COPY kvm/android-chrome-192x192.png /usr/share/kvmd/web/share/android-chrome-192x192.png

RUN chmod +x /linker/kvm/linker-kvm.sh

ENV SNLTTY_LINKER_IS_DOCKER="linker"
ENV DOTNET_ThreadPool_UnfairSemaphoreSpinLimit=0

ENTRYPOINT ["/linker/kvm/linker-kvm.sh"]