name: Publich
'on':
  workflow_dispatch: null
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
      - name: create release
        id: create_release
        uses: GongT/actions-recreate-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: v2.0.17
          release_name: v2.0.17.${{ steps.date.outputs.today }}
          draft: false
          prerelease: false
          body: "1. 请勿第一时间更新，建议延后2-3个小版本\r\n2. 隧道4字节长度头改为2长度+1消息类型(data/ping/pong/fin)+1保留\r\n3. UDP隧道支持策略冗余FEC和KCP\r\n4. 重写RFC5780NAT类型检测\r\n5. 端口转发和socks5底层逻辑合并\r\n6. 更多的Task向ValueTask优化\r\n7. 支持Mesh网络\r\n8. TCP/IP校验和全量扫描200ns改为增量更新10ns\r\n9. 可能的STUN端口预测\r\n10. 网络设备发现协议代理，支持海康SADP\r\n11. 修复APP闪退问题"
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          dotnet-version: 8.0.x
      - name: install dotnet maui
        run: dotnet workload install maui
      - name: publish projects
        run: ./shells/publish.bat "C:\\Android\\android-sdk"
      - name: upload-win-x86-oss
        id: upload-win-x86-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-win-x86.zip:/downloads/linker/v2.0.17/linker-win-x86.zip
          timeout: '720000'
      - name: upload-win-x86
        id: upload-win-x86
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-win-x86.zip
          asset_name: linker-win-x86.zip
          asset_content_type: application/zip
      - name: upload-win-x64-oss
        id: upload-win-x64-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-win-x64.zip:/downloads/linker/v2.0.17/linker-win-x64.zip
          timeout: '720000'
      - name: upload-win-x64
        id: upload-win-x64
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-win-x64.zip
          asset_name: linker-win-x64.zip
          asset_content_type: application/zip
      - name: upload-win-arm64-oss
        id: upload-win-arm64-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-win-arm64.zip:/downloads/linker/v2.0.17/linker-win-arm64.zip
          timeout: '720000'
      - name: upload-win-arm64
        id: upload-win-arm64
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-win-arm64.zip
          asset_name: linker-win-arm64.zip
          asset_content_type: application/zip
      - name: upload-linux-x64-oss
        id: upload-linux-x64-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-linux-x64.zip:/downloads/linker/v2.0.17/linker-linux-x64.zip
          timeout: '720000'
      - name: upload-linux-x64
        id: upload-linux-x64
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-linux-x64.zip
          asset_name: linker-linux-x64.zip
          asset_content_type: application/zip
      - name: upload-linux-arm-oss
        id: upload-linux-arm-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-linux-arm.zip:/downloads/linker/v2.0.17/linker-linux-arm.zip
          timeout: '720000'
      - name: upload-linux-arm
        id: upload-linux-arm
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-linux-arm.zip
          asset_name: linker-linux-arm.zip
          asset_content_type: application/zip
      - name: upload-linux-arm64-oss
        id: upload-linux-arm64-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-linux-arm64.zip:/downloads/linker/v2.0.17/linker-linux-arm64.zip
          timeout: '720000'
      - name: upload-linux-arm64
        id: upload-linux-arm64
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-linux-arm64.zip
          asset_name: linker-linux-arm64.zip
          asset_content_type: application/zip
      - name: upload-linux-musl-x64-oss
        id: upload-linux-musl-x64-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-linux-musl-x64.zip:/downloads/linker/v2.0.17/linker-linux-musl-x64.zip
          timeout: '720000'
      - name: upload-linux-musl-x64
        id: upload-linux-musl-x64
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-linux-musl-x64.zip
          asset_name: linker-linux-musl-x64.zip
          asset_content_type: application/zip
      - name: upload-linux-musl-arm-oss
        id: upload-linux-musl-arm-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-linux-musl-arm.zip:/downloads/linker/v2.0.17/linker-linux-musl-arm.zip
          timeout: '720000'
      - name: upload-linux-musl-arm
        id: upload-linux-musl-arm
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-linux-musl-arm.zip
          asset_name: linker-linux-musl-arm.zip
          asset_content_type: application/zip
      - name: upload-linux-musl-arm64-oss
        id: upload-linux-musl-arm64-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-linux-musl-arm64.zip:/downloads/linker/v2.0.17/linker-linux-musl-arm64.zip
          timeout: '720000'
      - name: upload-linux-musl-arm64
        id: upload-linux-musl-arm64
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-linux-musl-arm64.zip
          asset_name: linker-linux-musl-arm64.zip
          asset_content_type: application/zip
      - name: upload-osx-x64-oss
        id: upload-osx-x64-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-osx-x64.zip:/downloads/linker/v2.0.17/linker-osx-x64.zip
          timeout: '720000'
      - name: upload-osx-x64
        id: upload-osx-x64
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-osx-x64.zip
          asset_name: linker-osx-x64.zip
          asset_content_type: application/zip
      - name: upload-osx-arm64-oss
        id: upload-osx-arm64-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-osx-arm64.zip:/downloads/linker/v2.0.17/linker-osx-arm64.zip
          timeout: '720000'
      - name: upload-osx-arm64
        id: upload-osx-arm64
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-osx-arm64.zip
          asset_name: linker-osx-arm64.zip
          asset_content_type: application/zip
      - name: upload-anywhere-oss
        id: upload-anywhere-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: >-
            ./public/publish-zip/linker-anywhere.zip:/downloads/linker/v2.0.17/linker-anywhere.zip
          timeout: '720000'
      - name: upload-anywhere
        id: upload-anywhere
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker-anywhere.zip
          asset_name: linker-anywhere.zip
          asset_content_type: application/zip
      - name: upload-version-oss
        id: upload-version-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: ./version.txt:/downloads/linker/version.txt
          timeout: '720000'
      - name: upload-install-service-oss
        id: upload-install-service-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: ./src/linker/linker.service:/downloads/linker/linker.service
          timeout: '720000'
      - name: upload-install-oss
        id: upload-install-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: ./src/linker/linker-install.sh:/downloads/linker/linker-install.sh
          timeout: '720000'
      - name: upload-apk-oss
        id: upload-apk-oss
        uses: lslzl3000/oss-action@v1.0.1
        with:
          region: oss-cn-shenzhen
          key-id: ${{ secrets.ALIYUN_OSS_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_SECRET }}
          bucket: ide-qbcode
          assets: ./public/publish-zip/linker.apk:/downloads/linker/v2.0.17/linker.apk
          timeout: '720000'
      - name: upload-apk
        id: upload-apk
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/publish-zip/linker.apk
          asset_name: linker.apk
          asset_content_type: application/apk
